# Generated by Django 4.2.16 on 2025-10-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiket', 'verbose_name_plural': 'Etiketler'},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
