# Generated by Django 4.2.16 on 2025-10-17 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Blog', max_length=100)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('header_image_alt_text', models.CharField(blank=True, max_length=150)),
                ('site_background_color', models.CharField(default='#0052c9', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Geçerli bir hex renk kodu girin. Örn: #0052c9')])),
                ('site_text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Geçerli bir hex renk kodu girin. Örn: #0052c9')])),
                ('blog_post_background_color', models.CharField(default='#f0f0f0', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Geçerli bir hex renk kodu girin. Örn: #0052c9')])),
            ],
        ),
    ]
