# Generated by Django 4.2.16 on 2025-10-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Ayarlar', 'verbose_name_plural': 'Ayarlar'},
        ),
    ]
